"""
Response Schema Module.

Defines standardized response models used by all API endpoints.
Every response follows a consistent structure per API spec
(docs/07-API.md, Sections 8, 13, 14, 16).

Success Response:
    {
        "success": true,
        "data": { ... },
        "message": "..."
    }

Error Response:
    {
        "success": false,
        "error": {
            "code": "ERROR_CODE",
            "message": "Human-readable description."
        }
    }
"""

from typing import Any, Optional

from pydantic import BaseModel, Field


class ErrorDetail(BaseModel):
    """
    Structured error information returned in error responses.

    Attributes:
        code: Machine-readable error code (e.g., 'VALIDATION_ERROR').
        message: Human-readable error description.
    """

    code: str = Field(
        ...,
        description="Machine-readable error code.",
        examples=["VALIDATION_ERROR"],
    )
    message: str = Field(
        ...,
        description="Human-readable error message.",
        examples=["Programming language is required."],
    )


class SuccessResponse(BaseModel):
    """
    Standard response model for successful API operations.

    Attributes:
        success: Always True for successful responses.
        data: Response payload — structure varies by endpoint.
        message: Human-readable success message.
    """

    success: bool = Field(
        default=True,
        description="Indicates operation success.",
    )
    data: Any = Field(
        default=None,
        description="Response data payload.",
    )
    message: str = Field(
        default="Operation completed successfully.",
        description="Human-readable success message.",
    )


class ErrorResponse(BaseModel):
    """
    Standard response model for failed API operations.

    Attributes:
        success: Always False for error responses.
        error: Structured error details.
    """

    success: bool = Field(
        default=False,
        description="Indicates operation failure.",
    )
    error: ErrorDetail = Field(
        ...,
        description="Structured error information.",
    )


class HealthData(BaseModel):
    """
    Health check response data.

    Per API spec (docs/07-API.md, Section 12).
    """

    status: str = Field(
        default="healthy",
        description="Current service health status.",
    )
    service: str = Field(
        default="AI Code Review API",
        description="Service identifier.",
    )
    version: str = Field(
        default="1.0.0",
        description="Application version.",
    )


class ReviewData(BaseModel):
    """
    Review operation response data payload.

    Per API spec (docs/07-API.md, Section 13).
    """

    review: str = Field(
        ...,
        description="Markdown review text generated by the service.",
    )


class RewriteData(BaseModel):
    """
    Rewrite operation response data payload.

    Per API spec (docs/07-API.md, Section 14).
    """

    rewritten_code: str = Field(
        ...,
        description="Improved source code string generated by the service.",
    )
